@startuml casi_uso_slidesapp
left to right direction
actor Visitatore
actor Utente
Visitatore <|-- Utente

Visitatore --> (Visualizza elenco presentazioni)
Visitatore --> (Visualizza presentazione)
Visitatore --> (Autenticazione utente)

Utente --> (Crea presentazione)
Utente --> (Aggiungi slide)
Utente --> (Aggiungi immagine)
Utente --> (Modifica slide)


(Visualizza presentazione) .> (Visualizza elenco presentazioni) : <<extend>>
(Aggiungi slide) .> (Visualizza presentazione) : <<extend>>
@enduml

