services:
  - type: web
    name: slidesapp
    runtime: python
    rootDir: slides-app
    buildCommand: pip install -r requirements.txt && pybabel compile -d app/translations
    startCommand: gunicorn "app:create_app()" --bind 0.0.0.0:$PORT --workers 2
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: DATABASE
        value: /data/slides.sqlite
      - key: UPLOAD_FOLDER
        value: /data/uploads
    disk:
      name: slidesapp-data
      mountPath: /data
      sizeGB: 1
